before_install:
  - export TZ=America/Detroit

language: node_js

node_js:
  - 11

script:
  - CI=true npm test
  - npm run build

notifications:
  email:
    - rlreamy@umich.edu
    - zwright@umich.edu
    - cgates@umich.edu
    - rossmith@umich.edu
